### ISSUE TITLE
Fix Anchors' Behavior

### ISSUE THREAD

**Issue by ldanielw1** [gracepointboston/gracepointboston.org#6]
whenever you click on a link to an anchor (e.g. a section in a different page, like "Need a lift?" in the announcement bar), the  top nav usually covers the heading text. we should make it so that the heading shows below the top nav - needs to be a site wide behavior

**Comment by ldanielw1** [comment]
@baktistuta - does this look good now?

**Comment by baktistuta** [comment]
yes can we also fix it for "covocational ministry"?
- from the top nav
- from the about page

**Comment by ldanielw1** [comment]
hm... it looks good to me, do you have a screen resolution that it doesn't work at?

**Comment by baktistuta** [comment]
just using 14 inch macbook pro (3024 x 1964 pixels)
<img width="1095" alt="Screen Shot 2022-03-28 at 4 25 22 PM" src="https://user-images.githubusercontent.com/25651140/160481050-7bd077c7-5790-4efc-9dca-fb0803fdfb25.png">

**Comment by ldanielw1** [comment]
ok, increased padding
